### ISSUE TITLE
Possibly another name?

### ISSUE THREAD

**Issue by yerke** [kellpossible/commodity#1]
Hi,

Would you consider renaming the crate? Commodity is usually something non-currency, like oil, agricultural products (wheat, rice, etc.), precious metals (gold, silver, etc.) and so on.

From what I understand from README, your crate is more geared towards currencies. That is why name commodity is confusing.

Just a suggestion. Feel free to ignore/delete/burn this issue. :)

Yerke

**Comment by kellpossible** [comment]
Hi yerke, thanks for the suggestion, I did think about this quite a bit, and did initially think of naming it `currency` (although I think that one might already be taken)?.
This library could also be used to track the value of other commodities, like oil, products, shares, leave entitlements, etc. At the moment it is more geared towards monetary currencies, but I'm hoping, like in beancount, it can also be used for those other things too, which often interact with currencies anyway, so the chance of them existing in the same system is no insignificant. Perhaps I should consider renaming the `Currency` struct to something more generic like `CommodityType` to reduce confusion?

**Comment by kellpossible** [comment]
I've renamed some of the types to try and make the purpose of the library a little clearer.

**Comment by bugproof** [comment]
I preferred currency naming, maybe "Money" would be a better name? as it contains both value and currency. If I have `price: Commodity` in my struct it looks a bit weird. We can always use type alias `type Money = Commodity;`

**Comment by mightyiam** [comment]
I'm OK with commodity.
